"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NEWWINDOW = exports.THEME = exports.CATEGORIES = exports.SHOWHEADERTOP = exports.SHOWHEADERLINE = exports.SHOWHEADER = exports.PAGEICON = exports.PAGETITLE = void 0;
exports.PAGETITLE = "My Website";
exports.PAGEICON = "/logo.png";
exports.SHOWHEADER = true;
exports.SHOWHEADERLINE = true;
exports.SHOWHEADERTOP = false;
exports.CATEGORIES = "normal";
exports.THEME = "light";
exports.NEWWINDOW = true;
